import { schema } from "@pubrick/db";

// Fixed named allowlists; adding a table column never expands reads automatically.
export const billingPlanVersionsColumns = {
  id: schema.billingPlanVersions.id,
  planId: schema.billingPlanVersions.planId,
  version: schema.billingPlanVersions.version,
  priceId: schema.billingPlanVersions.priceId,
  price: schema.billingPlanVersions.price,
  limits: schema.billingPlanVersions.limits,
  provider: schema.billingPlanVersions.provider,
  environment: schema.billingPlanVersions.environment,
  accountId: schema.billingPlanVersions.accountId,
  createdAt: schema.billingPlanVersions.createdAt,
  updatedAt: schema.billingPlanVersions.updatedAt,
};
export const billingAccountsColumns = {
  orgId: schema.billingAccounts.orgId,
  customerId: schema.billingAccounts.customerId,
  customerKey: schema.billingAccounts.customerKey,
  customerIssuedAt: schema.billingAccounts.customerIssuedAt,
  customerRecoveryDeadline: schema.billingAccounts.customerRecoveryDeadline,
  deleted: schema.billingAccounts.deleted,
  revision: schema.billingAccounts.revision,
  provider: schema.billingAccounts.provider,
  environment: schema.billingAccounts.environment,
  accountId: schema.billingAccounts.accountId,
  createdAt: schema.billingAccounts.createdAt,
  updatedAt: schema.billingAccounts.updatedAt,
};
export const billingSubscriptionsColumns = {
  id: schema.billingSubscriptions.id,
  orgId: schema.billingSubscriptions.orgId,
  customerId: schema.billingSubscriptions.customerId,
  subscriptionId: schema.billingSubscriptions.subscriptionId,
  status: schema.billingSubscriptions.status,
  priceId: schema.billingSubscriptions.priceId,
  planVersionId: schema.billingSubscriptions.planVersionId,
  periodStart: schema.billingSubscriptions.periodStart,
  periodEnd: schema.billingSubscriptions.periodEnd,
  cancelAtPeriodEnd: schema.billingSubscriptions.cancelAtPeriodEnd,
  revision: schema.billingSubscriptions.revision,
  deleted: schema.billingSubscriptions.deleted,
  nextReconcileAt: schema.billingSubscriptions.nextReconcileAt,
  reconcileAttempts: schema.billingSubscriptions.reconcileAttempts,
  lastReconcileError: schema.billingSubscriptions.lastReconcileError,
  provider: schema.billingSubscriptions.provider,
  environment: schema.billingSubscriptions.environment,
  accountId: schema.billingSubscriptions.accountId,
  createdAt: schema.billingSubscriptions.createdAt,
  updatedAt: schema.billingSubscriptions.updatedAt,
};
export const organizationBillingStateColumns = {
  orgId: schema.organizationBillingState.orgId,
  revision: schema.organizationBillingState.revision,
  subscriptionId: schema.organizationBillingState.subscriptionId,
  planVersionId: schema.organizationBillingState.planVersionId,
  accessUntil: schema.organizationBillingState.accessUntil,
  access: schema.organizationBillingState.access,
  createdAt: schema.organizationBillingState.createdAt,
  updatedAt: schema.organizationBillingState.updatedAt,
};
export const billingCheckoutAttemptsColumns = {
  id: schema.billingCheckoutAttempts.id,
  orgId: schema.billingCheckoutAttempts.orgId,
  planVersionId: schema.billingCheckoutAttempts.planVersionId,
  priceId: schema.billingCheckoutAttempts.priceId,
  customerId: schema.billingCheckoutAttempts.customerId,
  checkoutId: schema.billingCheckoutAttempts.checkoutId,
  checkoutUrl: schema.billingCheckoutAttempts.checkoutUrl,
  customerKey: schema.billingCheckoutAttempts.customerKey,
  checkoutKey: schema.billingCheckoutAttempts.checkoutKey,
  successUrl: schema.billingCheckoutAttempts.successUrl,
  cancelUrl: schema.billingCheckoutAttempts.cancelUrl,
  issuedAt: schema.billingCheckoutAttempts.issuedAt,
  recoveryDeadline: schema.billingCheckoutAttempts.recoveryDeadline,
  status: schema.billingCheckoutAttempts.status,
  revision: schema.billingCheckoutAttempts.revision,
  leaseToken: schema.billingCheckoutAttempts.leaseToken,
  leaseExpiresAt: schema.billingCheckoutAttempts.leaseExpiresAt,
  nextAttemptAt: schema.billingCheckoutAttempts.nextAttemptAt,
  errorCode: schema.billingCheckoutAttempts.errorCode,
  deleted: schema.billingCheckoutAttempts.deleted,
  provider: schema.billingCheckoutAttempts.provider,
  environment: schema.billingCheckoutAttempts.environment,
  accountId: schema.billingCheckoutAttempts.accountId,
  createdAt: schema.billingCheckoutAttempts.createdAt,
  updatedAt: schema.billingCheckoutAttempts.updatedAt,
};
export const billingReceiptsColumns = {
  id: schema.billingReceipts.id,
  eventId: schema.billingReceipts.eventId,
  kind: schema.billingReceipts.kind,
  resourceId: schema.billingReceipts.resourceId,
  status: schema.billingReceipts.status,
  attempts: schema.billingReceipts.attempts,
  leaseToken: schema.billingReceipts.leaseToken,
  leaseExpiresAt: schema.billingReceipts.leaseExpiresAt,
  nextAttemptAt: schema.billingReceipts.nextAttemptAt,
  errorCode: schema.billingReceipts.errorCode,
  provider: schema.billingReceipts.provider,
  environment: schema.billingReceipts.environment,
  accountId: schema.billingReceipts.accountId,
  createdAt: schema.billingReceipts.createdAt,
  updatedAt: schema.billingReceipts.updatedAt,
};
export const billingCleanupColumns = {
  id: schema.billingCleanup.id,
  orgId: schema.billingCleanup.orgId,
  kind: schema.billingCleanup.kind,
  resourceId: schema.billingCleanup.resourceId,
  idempotencyKey: schema.billingCleanup.idempotencyKey,
  status: schema.billingCleanup.status,
  attempts: schema.billingCleanup.attempts,
  leaseToken: schema.billingCleanup.leaseToken,
  leaseExpiresAt: schema.billingCleanup.leaseExpiresAt,
  nextAttemptAt: schema.billingCleanup.nextAttemptAt,
  errorCode: schema.billingCleanup.errorCode,
  provider: schema.billingCleanup.provider,
  environment: schema.billingCleanup.environment,
  accountId: schema.billingCleanup.accountId,
  createdAt: schema.billingCleanup.createdAt,
  updatedAt: schema.billingCleanup.updatedAt,
};
