import { schema } from "@pubrick/db";

/** Reviewed public data fields. New columns never become exportable implicitly. */
export const WORKSPACE_EXPORT_TABLES = [
  {
    key: "aiTextSettings",
    table: schema.aiTextSettings,
    fields: ["orgId", "provider", "model", "revision"],
  },
  {
    key: "acceptedClaimCorrections",
    table: schema.acceptedClaimCorrections,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "reviewId",
      "fragmentVersionId",
      "claimIndex",
      "sourceBodyHash",
      "claim",
      "replacement",
      "reason",
      "evidence",
      "acceptedAt",
    ],
  },
  {
    key: "adaptationProposals",
    table: schema.adaptationProposals,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "adaptationId",
      "createdBy",
      "masterBody",
      "previousBody",
      "proposal",
      "reason",
      "createdAt",
    ],
  },
  {
    key: "adaptations",
    table: schema.adaptations,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "channelId",
      "body",
      "hashtags",
      "cta",
      "status",
      "origin",
      "scheduledAt",
      "attemptCount",
      "lastError",
      "failureReason",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "aiCredentials",
    table: schema.aiCredentials,
    fields: ["id", "orgId", "provider", "defaultModel", "createdAt", "updatedAt"],
  },
  {
    key: "autopilotConfigs",
    table: schema.autopilotConfigs,
    fields: [
      "brandId",
      "orgId",
      "enabled",
      "autoSuggestTopics",
      "semanticFilterBlockedTopics",
      "autoPlanTopics",
      "lastManualPlanAt",
      "channelIds",
      "timezone",
      "startHour",
      "quietStartHour",
      "quietEndHour",
      "dailyRunLimit",
      "planningDailyLimit",
      "dailySpendLimitUsd",
      "updatedAt",
    ],
  },
  {
    key: "autopilotDispatches",
    table: schema.autopilotDispatches,
    fields: ["id", "orgId", "brandId", "topicId", "runId", "localDate", "createdAt"],
  },
  { key: "brandAccess", table: schema.brandAccess, fields: ["orgId", "brandId", "memberId"] },
  { key: "brandFeeds", table: schema.brandFeeds, fields: ["id", "orgId", "brandId", "createdAt"] },
  {
    key: "brandPaidReplySettings",
    table: schema.brandPaidReplySettings,
    fields: [
      "brandId",
      "orgId",
      "sourceEnabled",
      "sourceRevision",
      "publicationEnabled",
      "publicationRevision",
      "dailyThresholdUsd",
      "thresholdRevision",
      "updatedAt",
    ],
  },
  {
    key: "brands",
    table: schema.brands,
    fields: [
      "id",
      "orgId",
      "name",
      "description",
      "voice",
      "audience",
      "contentLanguage",
      "linkPolicy",
      "automaticClaimEvidence",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "calendarSlots",
    table: schema.calendarSlots,
    fields: [
      "id",
      "orgId",
      "brandId",
      "scheduledAt",
      "brief",
      "contentType",
      "seoKeywords",
      "topicId",
      "manualPlanAttemptId",
      "topicTitle",
      "topicDescription",
      "topicSourceUrl",
      "topicUpdatedAt",
      "topicRevision",
      "channelIds",
      "generateCover",
      "generateInlineImages",
      "notes",
      "runId",
      "errorCode",
      "retryAfter",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "channels",
    table: schema.channels,
    fields: [
      "id",
      "orgId",
      "brandId",
      "platform",
      "name",
      "metricsAutoRefresh",
      "healthOk",
      "healthCheckedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "claimCorrectionProposals",
    table: schema.claimCorrectionProposals,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "reviewId",
      "claimIndex",
      "sourceBody",
      "sourceBodyHash",
      "claim",
      "replacement",
      "reason",
      "evidence",
      "createdAt",
    ],
  },
  {
    key: "claimReviews",
    table: schema.claimReviews,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "bodyHash",
      "trigger",
      "status",
      "claims",
      "errorCode",
      "unrecordedCalls",
      "createdAt",
      "startedAt",
      "completedAt",
    ],
  },
  {
    key: "clientReviewLinks",
    table: schema.clientReviewLinks,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "snapshotHash",
      "expiresAt",
      "revokedAt",
      "verdict",
      "comment",
      "reviewedAt",
      "createdBy",
      "createdAt",
    ],
  },
  {
    key: "contentImageSlots",
    table: schema.contentImageSlots,
    fields: [
      "id",
      "orgId",
      "brandId",
      "contentItemId",
      "mediaId",
      "afterParagraph",
      "alt",
      "caption",
      "alignment",
      "needsReview",
    ],
  },
  {
    key: "contentItems",
    table: schema.contentItems,
    fields: [
      "id",
      "orgId",
      "brandId",
      "title",
      "coverMediaId",
      "videoMediaId",
      "body",
      "richBody",
      "bodyRevision",
      "qualityScore",
      "imagesRevision",
      "status",
      "archivedFromStatus",
      "isSafeToDelete",
      "origin",
      "linkPolicyWebsite",
      "firstOpenedAt",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "contentVersions",
    table: schema.contentVersions,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "adaptationId",
      "body",
      "richBody",
      "title",
      "hashtags",
      "cta",
      "origin",
      "scope",
      "unitDelta",
      "runId",
      "createdBy",
      "createdAt",
    ],
  },
  {
    key: "draftRevisionProposals",
    table: schema.draftRevisionProposals,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "sourceBody",
      "sourceTitle",
      "instruction",
      "proposal",
      "proposedTitle",
      "imagePlan",
      "reason",
      "createdBy",
      "createdAt",
    ],
  },
  {
    key: "editorialNotes",
    table: schema.editorialNotes,
    fields: ["id", "orgId", "contentItemId", "bodyHash", "note", "createdBy", "createdAt"],
  },
  {
    key: "editorialPlaceholders",
    table: schema.editorialPlaceholders,
    fields: [
      "id",
      "orgId",
      "brandId",
      "date",
      "platform",
      "contentType",
      "timeOfDay",
      "notes",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "feedEntries",
    table: schema.feedEntries,
    fields: [
      "id",
      "orgId",
      "brandId",
      "feedId",
      "contentItemId",
      "adaptationId",
      "title",
      "body",
      "richBody",
      "publishedAt",
    ],
  },
  {
    key: "feedEntryImages",
    table: schema.feedEntryImages,
    fields: [
      "id",
      "orgId",
      "brandId",
      "feedEntryId",
      "mediaId",
      "afterParagraph",
      "alt",
      "caption",
      "alignment",
      "position",
    ],
  },
  {
    key: "knowledgeAutoIndex",
    table: schema.knowledgeAutoIndex,
    fields: ["brandId", "orgId", "enabled", "lastAttemptAt", "updatedAt"],
  },
  {
    key: "knowledgeEntries",
    table: schema.knowledgeEntries,
    fields: [
      "id",
      "orgId",
      "brandId",
      "title",
      "content",
      "category",
      "tags",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "mediaAssets",
    table: schema.mediaAssets,
    fields: [
      "id",
      "orgId",
      "brandId",
      "name",
      "kind",
      "mimeType",
      "width",
      "height",
      "byteSize",
      "createdAt",
    ],
  },
  {
    key: "memorableDates",
    table: schema.memorableDates,
    fields: [
      "id",
      "orgId",
      "brandId",
      "monthDay",
      "title",
      "leadDays",
      "suggestedContentTypes",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "newsCommentAnalyses",
    table: schema.newsCommentAnalyses,
    fields: [
      "itemId",
      "orgId",
      "brandId",
      "sampleCheckedAt",
      "sampleVersion",
      "result",
      "sampleSize",
      "createdAt",
    ],
  },
  {
    key: "newsCommentCollectionConfigs",
    table: schema.newsCommentCollectionConfigs,
    fields: ["brandId", "orgId", "enabled", "revision", "lastScannedAt", "updatedAt"],
  },
  {
    key: "newsComments",
    table: schema.newsComments,
    fields: [
      "id",
      "orgId",
      "brandId",
      "itemId",
      "telegramMessageId",
      "body",
      "publishedAt",
      "createdAt",
    ],
  },
  {
    key: "newsItems",
    table: schema.newsItems,
    fields: [
      "id",
      "orgId",
      "brandId",
      "sourceId",
      "title",
      "summary",
      "url",
      "publishedAt",
      "commentsStatus",
      "commentsCheckedAt",
      "commentsSampleVersion",
      "commentsErrorCode",
      "editorSignal",
      "dismissedAt",
      "dismissedPreviousSignal",
      "relevanceStatus",
      "relevanceScore",
      "relevanceFeedbackDelta",
      "relevanceReason",
      "relevanceUrgency",
      "relevanceErrorCode",
      "relevanceScoredAt",
      "relevanceAttempts",
      "createdAt",
    ],
  },
  {
    key: "newsSources",
    table: schema.newsSources,
    fields: [
      "id",
      "orgId",
      "brandId",
      "name",
      "kind",
      "url",
      "isActive",
      "checkIntervalMinutes",
      "lastCheckedAt",
      "lastErrorCode",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "notificationDigestConfigs",
    table: schema.notificationDigestConfigs,
    fields: ["brandId", "orgId", "enabled", "timezone", "localHour", "updatedAt"],
  },
  {
    key: "notificationDigestSnapshots",
    table: schema.notificationDigestSnapshots,
    fields: ["id", "orgId", "brandId", "localDate", "timezone", "summary", "message", "createdAt"],
  },
  {
    key: "notificationSettings",
    table: schema.notificationSettings,
    fields: ["orgId", "enabled", "draftReady", "deliveryProblem", "updatedAt"],
  },
  {
    key: "organizationApiKeys",
    table: schema.organizationApiKeys,
    fields: ["id", "orgId", "name", "prefix", "scope", "createdBy", "createdAt", "revokedAt"],
  },
  {
    key: "organizationPaidReplySettings",
    table: schema.organizationPaidReplySettings,
    fields: ["orgId", "timezone", "dailyThresholdUsd", "revision", "updatedAt"],
  },
  {
    key: "pipelineRuns",
    table: schema.pipelineRuns,
    fields: [
      "id",
      "orgId",
      "brandId",
      "topicId",
      "input",
      "guidanceSnapshot",
      "templateSnapshot",
      "status",
      "currentStep",
      "contentItemId",
      "error",
      "dismissedAt",
      "unrecordedCalls",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "promptDecisionRevisions",
    table: schema.promptDecisionRevisions,
    fields: ["id", "orgId", "decisionId", "role", "revisionId", "version", "decidedAt"],
  },
  {
    key: "promptDecisionTemplateRevisions",
    table: schema.promptDecisionTemplateRevisions,
    fields: [
      "id",
      "orgId",
      "decisionId",
      "role",
      "revisionId",
      "version",
      "isDefault",
      "decidedAt",
    ],
  },
  {
    key: "promptDecisions",
    table: schema.promptDecisions,
    fields: ["id", "orgId", "contentItemId", "ordinal", "runId", "verdict", "createdAt"],
  },
  {
    key: "promptRevisions",
    table: schema.promptRevisions,
    fields: ["id", "orgId", "role", "version", "guidance", "createdAt"],
  },
  {
    key: "publicationCommentAnalyses",
    table: schema.publicationCommentAnalyses,
    fields: [
      "publicationId",
      "orgId",
      "brandId",
      "sampleCheckedAt",
      "sampleVersion",
      "sampleSize",
      "result",
      "createdAt",
    ],
  },
  {
    key: "publicationCommentCollectionConfigs",
    table: schema.publicationCommentCollectionConfigs,
    fields: ["brandId", "orgId", "enabled", "revision", "lastScannedAt", "updatedAt"],
  },
  {
    key: "publicationCommentSamples",
    table: schema.publicationCommentSamples,
    fields: [
      "publicationId",
      "orgId",
      "brandId",
      "status",
      "requestedAt",
      "checkedAt",
      "sampleVersion",
      "errorCode",
    ],
  },
  {
    key: "publicationComments",
    table: schema.publicationComments,
    fields: ["id", "orgId", "brandId", "publicationId", "telegramMessageId", "body", "publishedAt"],
  },
  {
    key: "publicationMetrics",
    table: schema.publicationMetrics,
    fields: [
      "publicationId",
      "orgId",
      "status",
      "views",
      "likes",
      "comments",
      "shares",
      "checkedAt",
    ],
  },
  {
    key: "publications",
    table: schema.publications,
    fields: [
      "id",
      "orgId",
      "adaptationId",
      "channelId",
      "brandId",
      "channelName",
      "channelPlatform",
      "status",
      "externalId",
      "externalUrl",
      "error",
      "partialPrimaryKind",
      "partialPhotoId",
      "partialPhotoUrl",
      "partialFollowupText",
      "partialFollowupOutcome",
      "assertedBy",
      "assertedAt",
      "attempt",
      "createdAt",
    ],
  },
  {
    key: "refineProposals",
    table: schema.refineProposals,
    fields: [
      "id",
      "orgId",
      "contentItemId",
      "createdBy",
      "verb",
      "selectedText",
      "startOffset",
      "endOffset",
      "proposal",
      "reason",
      "createdAt",
    ],
  },
  {
    key: "roleTemplateHeads",
    table: schema.roleTemplateHeads,
    fields: ["orgId", "role", "activeRevisionId", "generation"],
  },
  {
    key: "roleTemplateRevisions",
    table: schema.roleTemplateRevisions,
    fields: ["id", "orgId", "role", "version", "source", "sourceSha256", "createdBy", "createdAt"],
  },
  {
    key: "searchCredentials",
    table: schema.searchCredentials,
    fields: ["orgId", "folderId", "updatedAt"],
  },
  {
    key: "topics",
    table: schema.topics,
    fields: [
      "id",
      "orgId",
      "brandId",
      "newsItemId",
      "title",
      "description",
      "contentType",
      "seoKeywords",
      "sourceUrl",
      "status",
      "blockedAt",
      "blockReason",
      "plannedDate",
      "priority",
      "origin",
      "suggestionKey",
      "inspirationKind",
      "inspirationRefId",
      "inspirationLabel",
      "inspirationDate",
      "revision",
      "createdAt",
      "updatedAt",
    ],
  },
  {
    key: "usageLedger",
    table: schema.usageLedger,
    fields: [
      "id",
      "analysisAdmissionId",
      "orgId",
      "brandId",
      "runId",
      "step",
      "channelId",
      "contentItemId",
      "adaptationId",
      "attempt",
      "provider",
      "modelId",
      "inputTokens",
      "outputTokens",
      "cachedInputTokens",
      "reasoningTokens",
      "costUsd",
      "costSource",
      "status",
      "outcome",
      "responseMs",
      "keyOwnership",
      "createdAt",
    ],
  },
  {
    key: "webhookSubscriptions",
    table: schema.webhookSubscriptions,
    fields: [
      "id",
      "orgId",
      "name",
      "onSucceeded",
      "onFailed",
      "onUnknown",
      "createdBy",
      "createdAt",
      "revokedAt",
    ],
  },
] as const;

/** Internal work and authentication state are deliberately excluded from user exports. */
export const WORKSPACE_EXPORT_OMISSIONS = {
  analysisAdmissions: "Operational admission leases",
  autopilotManualAttempts: "Operational dispatch attempts",
  autopilotScanEvents: "Operational scanner attempts",
  notificationEvents: "Operational notification deliveries",
  paidReplyAnalysisAttempts: "Encrypted transient paid analysis prompts",
  paidReplyAnalysisHandoffs: "Operational paid analysis dispatch",
  telegramLoginAttempts: "Authentication handshake secrets",
  telegramSourceAccounts: "Private Telegram session credentials",
  webhookDeliveries: "Operational webhook delivery payloads",
  searchRequests: "Operational search attempts",
  relevanceBatchItems: "Operational scoring attempts",
  relevanceBatches: "Operational scoring progress",
  topicSuggestionRequests: "Operational suggestions attempts",
  topicSuggestionScanDecisions: "Operational scanner decisions",
  manualTopicPlanAttempts: "Operational planning attempts",
} as const;
