-- 0017 — a delivery receipt can name the person who vouched for it.
--
-- WHY A COLUMN. An attempt whose answer never came back leaves the product
-- unable to say whether a post is live: the request left, the reply did not,
-- and `publications.status = 'unknown'` is the honest record of that. Nothing
-- in the product could move such a delivery afterwards — `approve` re-sends it
-- and may post a second copy, `reject` touches only outstanding rows, a receipt
-- needs a delivery — so the only way to finish the post was to delete the
-- channel. The resolver
-- (`POST /api/content/:id/adaptations/:adaptationId/delivery`) is the way out:
-- a person opens the channel, sees whether the post arrived, and says so.
--
-- What they say is written as an ordinary receipt — `published` or `failed` —
-- so every existing reader answers correctly with no change: the worker's
-- duplicate guard stops re-sending a post a human found live, and
-- `deliveryOutcome` stops reporting `unknown` once the last finished receipt
-- says otherwise. This column is what keeps such a receipt honest about its
-- OWN provenance. Without it a human's word is stored in the same shape as a
-- platform's answer, and the item screen renders it as "published — link
-- unavailable": a platform-confirmed delivery whose link went missing, which
-- is precisely what a human assertion is not.
--
-- `SET NULL`, NOT `CASCADE`, and the difference is the receipt itself. This
-- table outlives what it points at — both of its existing foreign keys are
-- nullable and `SET NULL` for that reason, and migration 0011 exists because
-- one of them was not. A `CASCADE` here would destroy the record of a delivery
-- because the person who vouched for it left the organisation. What their
-- departure costs is the NAME, not the fact.
--
-- WHICH IS WHY THERE ARE TWO COLUMNS, and this one is not a convenience. With
-- the fact recorded only as "`asserted_by` is not null", the sentence above is
-- false at the one place the fact is ever read: the api derives both the name
-- and the DATE through that pointer, so deleting the account takes the date
-- with it and the item screen falls back to "published — link unavailable" —
-- the platform-confirmed delivery this column exists to stop the product
-- claiming. `asserted_at` is written beside `asserted_by`, by the same
-- statement, from the same `now()` the receipt's own `created_at` defaults to,
-- and NO foreign key can reach it: after the account is gone the row still
-- says a person settled this delivery, and when.
--
-- ADDITIVE. Two nullable columns and one foreign key. No row is rewritten (both
-- columns arrive null on every existing receipt, which is what a
-- worker-written receipt means anyway), no existing value can stop being
-- valid, and there is no CHECK and no enum for a later value to fall foul of.
-- Nothing the WORKER reads changes shape either, so `docs/self-hosting.md`
-- §Upgrade's "worker first is always safe" stays true unamended.
ALTER TABLE "publications" ADD COLUMN "asserted_by" text;--> statement-breakpoint
ALTER TABLE "publications" ADD COLUMN "asserted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "publications" ADD CONSTRAINT "publications_asserted_by_user_id_fk" FOREIGN KEY ("asserted_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;
