import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { describe, expect, it } from "vitest";
import {
  decryptJson,
  encryptJson,
  isUnreadableCiphertext,
  parseKeyRing,
  rewrapJson,
  UNREADABLE_CREDENTIALS_MESSAGE,
  UnreadableCiphertextError,
} from "./crypto.js";

const KEY = Buffer.from(new Uint8Array(32).fill(7)).toString("base64");
const OTHER_KEY = Buffer.from(new Uint8Array(32).fill(9)).toString("base64");
const THIRD_KEY = Buffer.from(new Uint8Array(32).fill(11)).toString("base64");

/**
 * A blob written by the code this module replaces — `base64(iv || tag ||
 * ciphertext)` under `KEY`, with no version tag and no key id.
 *
 * FROZEN, not regenerated by a local copy of the old algorithm. A helper that
 * re-derived it would pass just as happily if both the helper and the reader
 * drifted together, which is the one thing this fixture exists to rule out:
 * every install that has ever run Pubrick has rows in exactly this shape, and
 * they have to keep opening.
 */
const LEGACY_UNDER_KEY =
  "fjPBTGeuYkqbDGwoC8zeTXoGJe31zx32Zuk9F+vI+TiVkHPxGJJheW7Q4kidKmb009Otsf6Jq20SrQ6VpZfhEaQX2AhZb/HU";
const LEGACY_PLAINTEXT = { botToken: "12345:abc", chatId: "@channel" };

/**
 * Opens a `p1.` envelope without going through `decryptJson`, so a test can see
 * the PLAINTEXT BYTES rather than the value they parse to.
 */
function openByHand(payload: string, keyBase64: string): string {
  const [, , body = ""] = payload.split(".");
  const raw = Buffer.from(body, "base64");
  const decipher = createDecipheriv(
    "aes-256-gcm",
    Buffer.from(keyBase64, "base64"),
    raw.subarray(0, 12),
  );
  decipher.setAuthTag(raw.subarray(12, 28));
  return Buffer.concat([decipher.update(raw.subarray(28)), decipher.final()]).toString("utf8");
}

/** The envelope's own fields, for the assertions about format rather than value. */
function envelope(payload: string): { version: string; keyId: string; body: string } {
  const [version = "", keyId = "", body = ""] = payload.split(".");
  return { version, keyId, body };
}

describe("crypto", () => {
  it("round-trips JSON values", () => {
    const secret = { botToken: "12345:abc", chatId: "@channel" };
    const payload = encryptJson(secret, KEY);
    expect(payload).not.toContain("12345:abc");
    expect(decryptJson(payload, KEY)).toEqual(secret);
  });

  it("produces different ciphertexts for the same input (random IV)", () => {
    expect(encryptJson("x", KEY)).not.toBe(encryptJson("x", KEY));
  });

  it("rejects a tampered payload", () => {
    const payload = encryptJson({ a: 1 }, KEY);
    const { version, keyId, body } = envelope(payload);
    const raw = Buffer.from(body, "base64");
    const byte = raw[raw.length - 1];
    if (byte !== undefined) {
      raw[raw.length - 1] = byte ^ 0xff;
    }
    const tampered = `${version}.${keyId}.${raw.toString("base64")}`;
    expect(() => decryptJson(tampered, KEY)).toThrow(UnreadableCiphertextError);
  });

  it("rejects the wrong key and a malformed key", () => {
    const payload = encryptJson({ a: 1 }, KEY);
    expect(() => decryptJson(payload, OTHER_KEY)).toThrow(UnreadableCiphertextError);
    expect(() => encryptJson("x", "dG9vLXNob3J0")).toThrow(/32 bytes/);
  });

  describe("the one event: a blob no configured key can open", () => {
    it("is one typed error carrying one sentence, for every way the data is unreadable", () => {
      const unreadable = [
        // A rotated key: written under a key this instance no longer has.
        () => decryptJson(encryptJson({ a: 1 }, OTHER_KEY), KEY),
        // A v1 envelope whose key id names no configured key.
        () => decryptJson(encryptJson({ a: 1 }, THIRD_KEY), `${KEY},${OTHER_KEY}`),
        // Truncated below iv+tag.
        () => decryptJson("bm90LWEtcmVhbC1ibG9i", KEY),
        // Not base64 of anything we wrote, in either format.
        () => decryptJson("p1.deadbeef.@@@@", KEY),
        () => decryptJson("p9.deadbeef.AAAA", KEY),
        () => decryptJson("p1.AAAA", KEY),
        // A legacy blob under a key that is not in the ring.
        () => decryptJson(LEGACY_UNDER_KEY, OTHER_KEY),
      ];
      for (const attempt of unreadable) {
        expect(attempt).toThrow(UnreadableCiphertextError);
        try {
          attempt();
        } catch (error) {
          expect(isUnreadableCiphertext(error)).toBe(true);
          expect((error as Error).message).toBe(UNREADABLE_CREDENTIALS_MESSAGE);
        }
      }
    });

    it("never leaks the crypto library's own sentence, which is what a screen used to print", () => {
      try {
        decryptJson(encryptJson({ a: 1 }, OTHER_KEY), KEY);
        throw new Error("expected a refusal");
      } catch (error) {
        expect((error as Error).message).not.toMatch(/unable to authenticate data/i);
        expect((error as Error).stack ?? "").not.toMatch(/unable to authenticate data/i);
      }
    });

    it("is NOT what a broken key ring produces — that is the instance, not the row", () => {
      // The distinction every caller routes on. A key that is not 32 bytes is an
      // operator's mistake about the whole install; reporting it as "your stored
      // credentials cannot be read" would be the same defect this module removes,
      // pointed the other way.
      for (const bad of ["", "   ", "dG9vLXNob3J0", `${KEY},dG9vLXNob3J0`, `${KEY},${KEY}`]) {
        let thrown: unknown;
        try {
          decryptJson(encryptJson({ a: 1 }, KEY), bad);
        } catch (error) {
          thrown = error;
        }
        expect(thrown).toBeInstanceOf(Error);
        expect(isUnreadableCiphertext(thrown)).toBe(false);
      }
    });

    it("covers authenticated ciphertext whose plaintext is not JSON", () => {
      // Our own key, our own tag, and still nothing usable. The envelope is
      // assembled here rather than through `encryptJson`, which cannot produce a
      // non-JSON plaintext — and that is the point: the reader must answer the
      // caller's question ("can I read the stored credentials?") the same way
      // whoever wrote the bytes.
      const key = Buffer.from(KEY, "base64");
      const keyId = createHash("sha256")
        .update("pubrick/credential-key-id/1")
        .update(key)
        .digest()
        .subarray(0, 4)
        .toString("hex");
      const iv = randomBytes(12);
      const cipher = createCipheriv("aes-256-gcm", key, iv);
      const ciphertext = Buffer.concat([cipher.update("{not json", "utf8"), cipher.final()]);
      const body = Buffer.concat([iv, cipher.getAuthTag(), ciphertext]).toString("base64");

      expect(() => decryptJson(`p1.${keyId}.${body}`, KEY)).toThrow(UnreadableCiphertextError);
    });

    it("recognises the marker by name, so a duplicated package copy still routes", () => {
      // `.name`, not `instanceof` — the same reason `classifyProbeFailure` gives.
      expect(isUnreadableCiphertext({ name: "UnreadableCiphertextError" })).toBe(true);
      expect(isUnreadableCiphertext(new Error("boom"))).toBe(false);
      expect(isUnreadableCiphertext(null)).toBe(false);
      expect(isUnreadableCiphertext("UnreadableCiphertextError")).toBe(false);
    });
  });

  describe("the envelope", () => {
    it("names its version and the key that wrote it", () => {
      const { version, keyId } = envelope(encryptJson({ a: 1 }, KEY));
      expect(version).toBe("p1");
      expect(keyId).toMatch(/^[0-9a-f]{8}$/);
    });

    it("gives different keys different ids, and the same key the same id every time", () => {
      const mine = envelope(encryptJson({ a: 1 }, KEY)).keyId;
      expect(envelope(encryptJson({ b: 2 }, KEY)).keyId).toBe(mine);
      expect(envelope(encryptJson({ a: 1 }, OTHER_KEY)).keyId).not.toBe(mine);
    });

    it("does not contain the key it was written with", () => {
      const payload = encryptJson({ a: 1 }, KEY);
      expect(payload).not.toContain(KEY);
      expect(payload).not.toContain(KEY.replace(/=+$/, ""));
    });

    it("is told apart from a legacy blob by a character base64 cannot contain", () => {
      // Not by a leading byte: a legacy blob starts with twelve bytes of random
      // IV, so one in 256 of them would begin with any byte a version could use.
      expect(LEGACY_UNDER_KEY).not.toContain(".");
      expect(encryptJson({ a: 1 }, KEY)).toContain(".");
    });
  });

  describe("reading what is already stored", () => {
    it("opens a blob written before this format existed", () => {
      expect(decryptJson(LEGACY_UNDER_KEY, KEY)).toEqual(LEGACY_PLAINTEXT);
    });

    it("opens a legacy blob with a key that is no longer the active one", () => {
      // The rotation itself: the new key is in front, the old one is still
      // behind it, and nothing was rewritten before the restart.
      expect(decryptJson(LEGACY_UNDER_KEY, `${OTHER_KEY},${KEY}`)).toEqual(LEGACY_PLAINTEXT);
    });

    it("opens a versioned blob written under a demoted key", () => {
      const written = encryptJson({ apiKey: "sk-old" }, KEY);
      expect(decryptJson(written, `${OTHER_KEY},${KEY}`)).toEqual({ apiKey: "sk-old" });
    });

    it("writes under the ring's ACTIVE key, never a trailing one", () => {
      const activeId = envelope(encryptJson({ a: 1 }, OTHER_KEY)).keyId;
      expect(envelope(encryptJson({ a: 1 }, `${OTHER_KEY},${KEY}`)).keyId).toBe(activeId);
      expect(decryptJson(encryptJson({ a: 1 }, `${OTHER_KEY},${KEY}`), OTHER_KEY)).toEqual({
        a: 1,
      });
    });
  });

  describe("rewrapping onto the active key", () => {
    it("moves a legacy blob onto the new key, and the new key alone then reads it", () => {
      const ring = `${OTHER_KEY},${KEY}`;
      const rewrapped = rewrapJson(LEGACY_UNDER_KEY, ring);
      expect(rewrapped).not.toBeNull();
      expect(rewrapped).not.toBe(LEGACY_UNDER_KEY);
      // The point of the whole exercise: the old key can now be dropped.
      expect(decryptJson(rewrapped as string, OTHER_KEY)).toEqual(LEGACY_PLAINTEXT);
      expect(envelope(rewrapped as string).keyId).toBe(
        envelope(encryptJson({ a: 1 }, OTHER_KEY)).keyId,
      );
    });

    it("moves a versioned blob off a demoted key", () => {
      const written = encryptJson({ apiKey: "sk-old" }, KEY);
      const rewrapped = rewrapJson(written, `${OTHER_KEY},${KEY}`) as string;
      expect(rewrapped).not.toBeNull();
      expect(decryptJson(rewrapped, OTHER_KEY)).toEqual({ apiKey: "sk-old" });
      expect(() => decryptJson(written, OTHER_KEY)).toThrow(UnreadableCiphertextError);
    });

    it("answers null — no write at all — for a blob already on the active key", () => {
      expect(rewrapJson(encryptJson({ a: 1 }, KEY), KEY)).toBeNull();
      expect(rewrapJson(encryptJson({ a: 1 }, `${KEY},${OTHER_KEY}`), `${KEY},${OTHER_KEY}`)).toBe(
        null,
      );
    });

    it("preserves the stored bytes exactly, rather than re-serialising the value", () => {
      // A rewrap must change the KEY and nothing else. Routing the plaintext
      // through `JSON.parse`/`JSON.stringify` would quietly rewrite what is
      // stored — `1.50` becomes `1.5`, an escape becomes a character, spacing
      // disappears — and no assertion made through `decryptJson` could ever see
      // it, because that reader normalises the same way. So the rewrapped bytes
      // are opened by hand.
      const stored = '{ "z": 1, "a": 2, "n": 1.50, "s": "\\u00e9" }';
      const key = Buffer.from(KEY, "base64");
      const iv = randomBytes(12);
      const cipher = createCipheriv("aes-256-gcm", key, iv);
      const legacy = Buffer.concat([
        iv,
        (() => {
          const body = Buffer.concat([cipher.update(stored, "utf8"), cipher.final()]);
          return Buffer.concat([cipher.getAuthTag(), body]);
        })(),
      ]).toString("base64");

      const rewrapped = rewrapJson(legacy, `${OTHER_KEY},${KEY}`) as string;
      expect(rewrapped).not.toBeNull();
      expect(openByHand(rewrapped, OTHER_KEY)).toBe(stored);
      // And the value it carries is still the value.
      expect(decryptJson(rewrapped, OTHER_KEY)).toEqual({ z: 1, a: 2, n: 1.5, s: "é" });
    });

    it("leaves a legacy blob alone under a ring of ONE — there is no key to move it off", () => {
      // Every existing install runs a single key, and its rows are in the legacy
      // shape. Re-sealing one here would change its FORMAT and nothing else, and
      // a worker still on the previous build reads only the legacy format: a
      // rolling deploy that brings the api up first would then break every post
      // for the first channel anyone pressed Test on. So the answer is "nothing
      // to do", and the stored bytes — the old code's own output — are untouched.
      expect(rewrapJson(LEGACY_UNDER_KEY, KEY)).toBeNull();
      // ...and the very same blob DOES move once a second key is in the ring,
      // whichever position the key that wrote it now holds.
      expect(rewrapJson(LEGACY_UNDER_KEY, `${OTHER_KEY},${KEY}`)).not.toBeNull();
      expect(rewrapJson(LEGACY_UNDER_KEY, `${KEY},${OTHER_KEY}`)).not.toBeNull();
    });

    it("still refuses an unreadable blob under a ring of one, rather than reading the no-op as success", () => {
      expect(() => rewrapJson(encryptJson({ a: 1 }, THIRD_KEY), KEY)).toThrow(
        UnreadableCiphertextError,
      );
      expect(() => rewrapJson("not-a-blob", KEY)).toThrow(UnreadableCiphertextError);
    });

    it("refuses a blob it cannot open rather than quietly leaving it alone", () => {
      expect(() => rewrapJson(encryptJson({ a: 1 }, THIRD_KEY), `${KEY},${OTHER_KEY}`)).toThrow(
        UnreadableCiphertextError,
      );
    });
  });

  describe("parseKeyRing", () => {
    it("accepts a single key — every value that has ever been deployed", () => {
      expect(parseKeyRing(KEY)).toEqual([KEY]);
    });

    it("keeps ring order, active key first, and tolerates spacing", () => {
      expect(parseKeyRing(` ${KEY} , ${OTHER_KEY} `)).toEqual([KEY, OTHER_KEY]);
    });

    it("refuses an empty ring, a short key anywhere in it, and a repeated key", () => {
      expect(() => parseKeyRing("")).toThrow(/32 bytes/);
      expect(() => parseKeyRing(" , ")).toThrow(/32 bytes/);
      expect(() => parseKeyRing(`${KEY},dG9vLXNob3J0`)).toThrow(/32 bytes/);
      expect(() => parseKeyRing(`dG9vLXNob3J0,${KEY}`)).toThrow(/32 bytes/);
      expect(() => parseKeyRing(`${KEY},${KEY}`)).toThrow(/repeat/);
    });
  });
});
